version: '3'

# Named volumes
volumes:
  # MySQL Data
  todolist-mysql-data:
    driver: local

services:
  
  # MySQL (5.7)
    mysql:
        image: mysql:5.7
        container_name: todolist-mysql
        volumes:
        - todolist-mysql-data:/var/lib/mysql
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=todolist
        - MYSQL_DATABASE=todolist
        - MYSQL_USER=todolist
        - MYSQL_PASSWORD=todolist


  # PHP (with Nginx)
    app:
        image: ambientum/php:7.3-nginx
        container_name: todolist-app
        volumes:
        - .:/var/www/app
        ports:
        - 8080:8080
        links:
        - mysql
